[build]
  # Para sitios estáticos, publicamos desde la raíz
  publish = "."
  # No necesitamos comando de build
  command = "echo 'Static site deployed'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configuración para funciones serverless (si las usas)
[functions]
  directory = "netlify/functions"